### ISSUE TITLE
checksum error for version 0.2.0

### ISSUE THREAD

**Issue by akadoya** [johnbellone/consul-replicate-cookbook#2]
when I try to install/configure v0.2.0 by including this cookbook's default recipe into my wrapper recipe, kitchen test failed with checksum error.

```
           * remote_file[consul-replicate_0.2.0_linux_amd64.zip] action create

             ================================================================================
             Error executing action `create` on resource 'remote_file[consul-replicate_0.2.0_linux_amd64.zip]'
             ================================================================================

             Chef::Exceptions::ChecksumMismatch
             ----------------------------------
             Checksum on resource (591d07) does not match checksum on content (cc7ffb)

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:49:in `block in run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `run_action'
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
             /tmp/kitchen/cache/cookbooks/consul-replicate/libraries/consul_replicate_installation_archive.rb:40:in `action_create'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

             Resource Declaration:
             ---------------------
       # In /tmp/kitchen/cache/cookbooks/consul-replicate/libraries/consul_replicate_installation_archive.rb

       52:           remote_file ::File.basename(url) do
       53:             action :nothing
       54:             source url
       55:             checksum options[:archive_checksum]
       56:             path ::File.join(Chef::Config[:file_cache_path], name)
       57:           end
       58:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/consul-replicate/libraries/consul_replicate_installation_archive.rb:52:in `block in action_create'

             remote_file("consul-replicate_0.2.0_linux_amd64.zip") do
        provider Chef::Provider::RemoteFile
        action [:nothing]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        source ["https://releases.hashicorp.com/consul-replicate/0.2.0/consul-replicate_0.2.0_linux_amd64.zip"]
        use_etag true
        use_last_modified true
        declared_type :remote_file
        cookbook_name "consul-replicate"
        checksum "591d073718ec9abeaf5974e9e9d8c058780342c5a14dade059f8082173549fe8"
        path "/tmp/kitchen/cache/consul-replicate_0.2.0_linux_amd64.zip"
             end
```

when I tried to install v0.1.0 this didn't happen.

**Comment by akadoya** [comment]
I am using ubuntu14.04 64bit by the way

**Comment by akadoya** [comment]
this might be because of poise-archive or something else.. now I could install 0.2.0 with no problem
